project/blog/urls.py
from django.urls import path
from .import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), # /blog/
    path('add/', views.AddView.as_view(), name='add'), # /blog/add
    path('update/<int:pk>/', views.UpdateView.as_view(), name='update'), #/blog/update/1 <int:pk>整数ならなんでも受け取る
    path('delete/<int:pk>/', views.DeleteView.as_view(), name='delete'), #/blog/delete/1
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'), #/blog/detail/1/
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

project/blog/models.py
from django.db import models
from django.utils import timezone #djangoでは、datetime.nowのかわりに, timezon.nowで現在の日付・時刻を取得する


class Day(models.Model):
    # id = models.AutoField(primary_key=True) #自動で追加されてる 重複が許されない
    title = models.CharField('タイトル', max_length=200)
    text = models.TextField('本文')
    date = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return self.title

project/blog/forms.py
from  django import forms
from .models import Day


class DayCreateForm(forms.ModelForm):

    class Meta:
        model = Day
        fields = '__all__' #('title', 'text', 'date')タプルで指定する

project/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from .forms import DayCreateForm
from .models import Day


class IndexView(generic.ListView):
    model = Day
    paginate_by = 3 # 3件ずつ


class AddView(LoginRequiredMixin, generic.CreateView):
    model = Day
    form_class = DayCreateForm # fields = '__all__'でもかける
    success_url = reverse_lazy('blog:index') # /blog/


class UpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Day
    form_class = DayCreateForm
    success_url = reverse_lazy('blog:index')

class DeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Day
    success_url = reverse_lazy('blog:index')


class DetailView(generic.DetailView):
    model = Day

 
'''
def index(request):
    context = {
        'day_list': Day.objects.all(),
    }
    return render(request, 'blog/day_list.html', context)


def add(request):
    # 送信内容を基にフォームを作る。POSTでなければ空フォーム
    form = DayCreateForm(request.POST or None)

    # method=POST,送信ボタンを押した時、入力内容が問題なければ
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('blog:index')

    # 通常のアクセスページや、入力内容に誤りがあればまたぺーじを表示
    context = {
        'form': form
    }
    return render(request, 'blog/day_form.html', context)


def update(request, pk):
    # urlのpkを基にDayを取得
    day = get_object_or_404(Day, pk=pk)

    #フォームに取得したDayを紐付ける
    form = DayCreateForm(request.POST or None, instance=day)

    # method=POST, つまり送信ボタンを押した時、入力なうように問題がなければ
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('blog:index')

    # 通常時のページアクセスや、入力内容に誤りがあればまたページを表示
    context = {
        'form': form,
    }
    return render(request, 'blog/day_form.html', context)

def delete(request, pk):
    # urlのpkを基にDayを取得
    day = get_object_or_404(Day, pk=pk)

    # method=POST, つまり送信ボタンを押した時、入力なうように問題がなければ
    if request.method == 'POST':
        day.delete()
        return redirect('blog:index')

    # 通常時のページアクセスや、入力内容に誤りがあればまたページを表示
    context = {
        'day': day,
    }
    return render(request, 'blog/day_confirm_delete.html', context)


def detail(request, pk):
    # urlのpkを基にDayを取得
    day = get_object_or_404(Day, pk=pk)

    # 通常時のページアクセスや、入力内容に誤りがあればまたページを表示
    context = {
        'day': day,
    }
    return render(request, 'blog/day_detail.html', context)
'''

project/blog/templates/blog/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>日記アプリケーション</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <nav class="nav">
          <a class="nav-link active" href="{% url 'blog:index' %}">一覧</a>
          <a class="nav-link" href="{% url 'blog:add' %}">追加</a>

        </nav>
        
      {% block content %}
      {% endblock %}
    </div>    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

project/blog/templates/blog/day_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>タイトル</th>
            <th>{{ day.title }}</th>
        </tr>
        <tr>
            <th>本文</th>
            <th>{{ day.text }}</th>
        </tr>
        <tr>
            <th>日付</th>
            <th>{{ day.date }}</th>
        </tr>
    </table>
    <p>こちらのデータを削除します。</p>
    <button type="submit" class="btn btn-primary">送信</button>
{% csrf_token %}
</form>
{% endblock %}

project/blog/templates/blog/day_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <table class="table">
        <tr>
            <th>タイトル</th>
            <th>{{ day.title }}</th>
        </tr>
        <tr>
            <th>本文</th>
            <th>{{ day.text | linebreaksbr}}</th>
        </tr>
        <tr>
            <th>日付</th>
            <th>{{ day.date }}</th>
        </tr>
    </table>
</form>
{% endblock %}

project/blog/templates/blog/day_form.html
{% extends 'blog/base.html' %}

{% block content %}
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>タイトル</th>
            <th>{{ form.title }}</th>
        </tr>
        <tr>
            <th>本文</th>
            <th>{{ form.text }}</th>
        </tr>
        <tr>
            <th>日付</th>
            <th>{{ form.date }}</th>
        </tr>
    </table>
    <button type="submit" class="btn btn-primary">送信</button>
{% csrf_token %}
</form>
{% endblock %}

project/blog/templates/blog/day_list.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>日記一覧</h1>
<table class="table">
    <thead>
        <tr>
            <th>タイトル</th>
            <th>日付</th>
            <th>#</th>
            <th>#</th>
        </tr>
    </thead>
    <tbody>
    {% for day in day_list %}
        <tr>
            <td><a href="{% url 'blog:detail' day.pk %}">{{ day.title }}</a></td>
            <td>{{ day.date }}</td>
            <td><a href="{% url 'blog:update' day.pk %}">更新</a></td>
            <td><a href="{% url 'blog:delete' day.pk %}">削除</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% include 'blog/page4.html' %}

{% endblock %}

project/blog/templates/blog/page1.html
<!-- 前への部分 -->
{% if page_obj.has_previous %}
<a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}


<!-- 次への部分 -->
{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %} 

project/blog/templates/blog/page2.html
<!-- 前への部分 -->
{% if page_obj.has_previous %}
<a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

<!-- 数字の部分 -->
{% for num in page_obj.paginator.page_range %}
 {% if page_obj.number == num %}
  <span>{{ num }}</span>
  {% else %}
    <a href="?page={{ num }}">{{ num }}</a>
  {% endif %}
{% endfor %}


<!-- 次への部分 -->
{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}

project/blog/templates/blog/page3.html
<!-- 前へ の部分 -->
{% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

<!-- 数字の部分 -->
Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
 
<!-- 次へ の部分 -->
{% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}

project/blog/templates/blog/page4.html
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ link_page }}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ link_page }}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>